name: build

on: [push, pull_request]

jobs:
  # test:
    # strategy:
    #   matrix:
    #     platform: [ubuntu-latest, macOS-latest]
    #     node: [12.x, 10.x]
    # name: test/node ${{ matrix.node-version }}
    # runs-on: ${{ matrix.os }}
    # steps:
    #   - uses: actions/checkout@master
    #   - uses: actions/setup-node@master
    #     with:
    #       node-version: ${{ matrix.node-version }}
    #   - run: npm install
    #   - run: npm run build --if-present
    #   - run: npm test
    #     env:
    #       CI: true
  coverage:
    # needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '12'
      - run: npm install
      - name: Test and publish code coverage
        uses: paambaati/codeclimate-action@v2.4.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CodeClimateReporterId }}
        with:
          coverageCommand: npx jest --coverage
          debug: true
